name: "Build All Flake Packages"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Flake Check
      run: nix flake check
    
    - name: Build All Packages
      run: |
        # Get all package names from the flake
        PACKAGES=$(nix eval --json .#packages.x86_64-linux --apply builtins.attrNames | jq -r '.[]')
        
        # Build each package
        for pkg in $PACKAGES; do
          echo "Building package: $pkg"
          nix build .#$pkg || exit 1
        done
